"""Testing

Revision ID: 62616f798234
Revises: 0dae71a81c6f
Create Date: 2025-04-21 10:35:23.880897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62616f798234'
down_revision: Union[str, None] = '0dae71a81c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('test', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
