"""Add User table and Add Relationship for To Do Table

Revision ID: ff76dad73be0
Revises: 512c51282c83
Create Date: 2025-04-24 22:29:08.119358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff76dad73be0'
down_revision: Union[str, None] = '512c51282c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Chỉ thêm cột user_id và khóa ngoại vào todo_task
    with op.batch_alter_table('todo_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_todo_task_user_id', 'users', ['user_id'], ['id'])
    
    # Gán giá trị mặc định cho user_id (nếu có dữ liệu trong todo_task)
    op.execute("UPDATE todo_task SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL")
    
    # Đặt user_id thành NOT NULL
    with op.batch_alter_table('todo_task', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Xóa cột user_id và khóa ngoại
    with op.batch_alter_table('todo_task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_task_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
